### ISSUE TITLE
How to run

### ISSUE THREAD

**Issue by tsmitsmitonline** [sharsil/mailcat#1]
I downloaded the mailcat.py app, try to run it via "./mailcat.py USERNAME', but the result is:

Traceback (most recent call last):
  File "./mailcat.py", line 14, in <module>
    import dns.resolver
ModuleNotFoundError: No module named 'dns'

What is going wrong?

**Comment by soxoj** [comment]
I added the `requirements.txt` file with dependencies, please run `pip3 install -r requirements.txt` and try again. Also added instruction to README.

**Comment by tsmitsmitonline** [comment]
Thanks, it works now.
1 last question: do the email results from your app mean that these are valid (existing) mail addresses?

**Comment by soxoj** [comment]
Yes, exactly.

**Comment by tsmitsmitonline** [comment]
I experience another result. When I search on 'smitonline' (my username), I get a protonmail as a return (and more); smitonline@protonmail.com. When I send an email to smitonline@protonmail.com, I get a return message (undeliverable).

**Comment by sharsil** [comment]
> I experience another result. When I search on 'smitonline' (my username), I get a protonmail as a return (and more); [smitonline@protonmail.com](mailto:smitonline@protonmail.com). When I send an email to [smitonline@protonmail.com](mailto:smitonline@protonmail.com), I get a return message (undeliverable).

Sorry for the delay in getting back to you! Here is a new interesting problem with Proton API - all received answers are false-positives,  we made another way to check existing mails. Thanks!
