### ISSUE TITLE
help me please

### ISSUE THREAD

**Issue by Faisa1245** [sharsil/mailcat#20]
python3 ./mailcat.py   **********

Traceback (most recent call last):
  File "/home/kali/mailcat/./mailcat.py", line 10, in <module>
    import aiosmtplib
ModuleNotFoundError: No module named 'aiosmtplib'

**Comment by Faisa1245** [comment]
Thanks the solution is : pip3 install aiosmtplib

**Comment by soxoj** [comment]
Fixed in 0001a65d165d4f2bfdceaebf51a5cc3073b2219e, thank you
