### ISSUE TITLE
Update requirements

### ISSUE THREAD

**Issue by R3dHash** [sharsil/mailcat#21]
add aiosmtplib to requirements allowed me to run the script without throwing that error:
Traceback (most recent call last):
```
File "mailcat.py", line 10, in <module>
    import aiosmtplib
ModuleNotFoundError: No module named 'aiosmtplib'
```

**Comment by soxoj** [comment]
Fixed in 0001a65d165d4f2bfdceaebf51a5cc3073b2219e, thank you
