### ISSUE TITLE
module 'aiosmtplib.esmtp' has no attribute 'ESMTP'

### ISSUE THREAD

**Issue by C3n7ral051nt4g3ncy** [sharsil/mailcat#26]
Hi, any help appreciated.

In order to avoid errors:

- I am using a `virtualenv `
- Python 3.9.16

<img width="644" src="https://user-images.githubusercontent.com/104733166/216976584-dc2caf97-0919-41f4-a3c8-69632a69885f.png">

**Comment by soxoj** [comment]
Hey, sorry for the delay, I'll discuss it with @P3run and will make a fix

**Comment by soxoj** [comment]
Should be fixed

**Comment by C3n7ral051nt4g3ncy** [comment]
Thank you @soxoj
