### ISSUE TITLE
Cannot lauch script (Win7, cert failed / smtp error)

### ISSUE THREAD

**Issue by Salomeaser** [sharsil/mailcat#29]
When i try to launch the script with python i get :

Error while checking gmail: module 'aiosmtplib.esmtp' has no attribute 'ESMTP'
Error while checking yandex: module 'aiosmtplib.esmtp' has no attribute 'ESMTP'
Error while checking mailDe: module 'aiosmtplib.esmtp' has no attribute 'ESMTP'
Yahoo:
*  ayoubmekouar@yahoo.com
Error while checking tutby: Cannot connect to host profile.tut.by:443 ssl:True [SSLCertVerificationError: (1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'profile.tut.by'. (_ssl.c:997)")]

Please help me through

**Comment by soxoj** [comment]
Hey, what versions of Python and aiosmtplib do you have?

**Comment by Salomeaser** [comment]
Hello,

I work about Python  3 and Windows 7 Professionnal and mail cat not
fonctionne

Thanks,

**Comment by soxoj** [comment]
@Salomeaser please, send a full log of last mailcat version execution with errors

**Comment by soxoj** [comment]
Outdated, closing.
